### ISSUE TITLE
Conversion API Free Limit Reached

### ISSUE THREAD

**Issue by rajpiskala** [matthewcn56/howmanybobascouldmatthaveboughtwiththemoneyhespentondomains#21]
Going to the website displays that Matt spends "NaN USD" every year on domains. Looking at the network response, the GET request to free.currconv.com is failing with an error 400 with a message "Free API limit reached."

Since the API limit was reached, you may need to refresh or upgrade your API key. I can add caching on the front end for API requests to reduce the likelihood that this happens again.

**Comment by matthewcn56** [comment]
That would be great! It looks like we have to implement error checks to ensure that we still display things properly even if API limits are reached.

**Comment by matthewcn56** [comment]
closed by #22
