### ISSUE TITLE
Use user location to determine tax

### ISSUE THREAD

**Issue by dtjanaka** [matthewcn56/howmanybobascouldmatthaveboughtwiththemoneyhespentondomains#6]

**Comment by dtjanaka** [comment]
TODO(dtjanaka):

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

https://developers.google.com/maps/documentation/geocoding/overview#ReverseGeocoding

**Comment by dtjanaka** [comment]
Expanding scope to displaying local currency. Perhaps determine boba prices per country? @matthewcn56

**Comment by matthewcn56** [comment]
> Expanding scope to displaying local currency. Perhaps determine boba prices per country? @matthewcn56

ooh localization would be a nice thing to add! I think it's a big enough change to warrant its own PR afterwards

**Comment by dtjanaka** [comment]
Correct API (https://developers.google.com/maps/documentation/geocoding/overview#ReverseGeocoding is for server-side):
https://developers.google.com/maps/documentation/javascript/geocoding#ReverseGeocoding

Note: need to enable both Maps JS API and Geocoding API.

**Comment by dtjanaka** [comment]
Potentially useful:
https://www.npmjs.com/package/sales-tax
https://stackoverflow.com/a/8391430
